# Modify this line to contain the path to the directory that contains
# libmongo.a and src
#LIB = ../../../mongo-c-driver/src


wordfreq: hello.c
	cc hello.c `pkg-config --cflags --libs glib-2.0` -o wordfreq